[0KRunning with gitlab-runner 13.8.0 (775dd39d)
[0;m[0K  on docker-runner ckd-HWTy
[0;msection_start:1613585657:prepare_executor[0K[0K[36;1mPreparing the "docker" executor[0;m
[0;m[0KUsing Docker executor with image docker:19.03.12 ...
[0;m[0KStarting service docker:19.03.12-dind ...
[0;m[0KAuthenticating with credentials from /root/.docker/config.json
[0;m[0KPulling docker image docker:19.03.12-dind ...
[0;m[0KUsing docker image sha256:66dc2d45749a48592f4348fb3d567bdd65c9dbd5402a413b6d169619e32f6bd2 for docker:19.03.12-dind with digest docker@sha256:674f1f40ff7c8ac14f5d8b6b28d8fb1f182647ff75304d018003f1e21a0d8771 ...
[0;m[0KWaiting for services to be up and running...
[0;m
[0;33m*** WARNING:[0;m Service runner-ckd-hwty-project-2-concurrent-0-35183c18f64221c4-docker-0 probably didn't start properly.

Health check error:
start service container: Error response from daemon: Cannot link to a non running container: /runner-ckd-hwty-project-2-concurrent-0-35183c18f64221c4-docker-0 AS /runner-ckd-hwty-project-2-concurrent-0-35183c18f64221c4-docker-0-wait-for-service/service (docker.go:1270:0s)

Service container logs:
2021-02-17T18:14:27.221128718Z mount: permission denied (are you root?)
2021-02-17T18:14:27.224712911Z Could not mount /sys/kernel/security.
2021-02-17T18:14:27.224847909Z AppArmor detection and --privileged mode might break.
2021-02-17T18:14:27.237660243Z mount: permission denied (are you root?)

[0;33m*********[0;m

[0KAuthenticating with credentials from /root/.docker/config.json
[0;m[0KPulling docker image docker:19.03.12 ...
[0;m[0KUsing docker image sha256:81f5749c9058a7284e6acd8e126f2b882765a17b9ead14422b51cde1a110b85c for docker:19.03.12 with digest docker@sha256:d41efe7ad0df5a709cfd4e627c7e45104f39bbc08b1b40d7fb718c562b3ce135 ...
[0;msection_end:1613585675:prepare_executor[0Ksection_start:1613585675:prepare_script[0K[0K[36;1mPreparing environment[0;m
[0;mRunning on runner-ckd-hwty-project-2-concurrent-0 via 0d419e5de8cf...
section_end:1613585677:prepare_script[0Ksection_start:1613585677:get_sources[0K[0K[36;1mGetting source from Git repository[0;m
[0;m[32;1mFetching changes with git depth set to 50...[0;m
Reinitialized existing Git repository in /builds/root/cicd-telkomsel/.git/
fatal: unable to access 'http://gitlab.example.com/root/cicd-telkomsel.git/': Could not resolve host: gitlab.example.com
section_end:1613585679:get_sources[0Ksection_start:1613585679:upload_artifacts_on_failure[0K[0K[36;1mUploading artifacts for failed job[0;m
[0;m[32;1mUploading artifacts...[0;m
[0;33mWARNING: gl-code-quality-report.json: no matching files[0;m 
[31;1mERROR: No files to upload                         [0;m 
section_end:1613585681:upload_artifacts_on_failure[0K[31;1mERROR: Job failed: exit code 1
[0;m